# Generated by Django 3.1.4 on 2022-03-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAndCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.CharField(max_length=255)),
                ('council', models.CharField(max_length=255)),
                ('ethnicity', models.CharField(max_length=255)),
                ('certificationDescription', models.CharField(max_length=255)),
                ('expirationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentationDescription', models.CharField(default='N', max_length=266)),
                ('numberOfEmployees', models.IntegerField()),
                ('taxIdVatNumber', models.CharField(max_length=266)),
                ('totalAnnaulSales', models.CharField(max_length=266)),
                ('DunsNumber', models.CharField(max_length=266)),
                ('qualityCertification', models.CharField(max_length=266)),
                ('certificationExpectedDate', models.DateTimeField()),
                ('operationOutsideUsa', models.CharField(max_length=266)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('jobTitle', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('MobileNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NaLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NpmCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NpmSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OEMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.CharField(max_length=255)),
                ('council', models.CharField(max_length=255)),
                ('ethnicity', models.CharField(max_length=255)),
                ('certificationDescription', models.CharField(max_length=255)),
                ('expirationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PmCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PmSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAndService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npmValue', models.CharField(max_length=255)),
                ('npmValueCategory1', models.CharField(max_length=255)),
                ('npmValueCategory2', models.CharField(max_length=255)),
                ('pmValue', models.CharField(max_length=255)),
                ('pmValueCategory1', models.CharField(max_length=255)),
                ('pmValueCategory2', models.CharField(max_length=255)),
                ('additoinalProductAndServices', models.CharField(max_length=1055)),
            ],
        ),
        migrations.CreateModel(
            name='SalesContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('jobTitle', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('MobileNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VeteranOwnedBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.CharField(max_length=255)),
                ('council', models.CharField(max_length=255)),
                ('ethnicity', models.CharField(max_length=255)),
                ('certificationDescription', models.CharField(max_length=255)),
                ('expirationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WomenOwnedBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.CharField(max_length=255)),
                ('council', models.CharField(max_length=255)),
                ('ethnicity', models.CharField(max_length=255)),
                ('certificationDescription', models.CharField(max_length=255)),
                ('expirationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCapabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOem', models.BooleanField()),
                ('AbcSupplier', models.BooleanField()),
                ('vendorNumber', models.IntegerField()),
                ('anyOtherTier1AutomotiveCompany', models.BooleanField()),
                ('VMI', models.BooleanField()),
                ('percentageSale', models.IntegerField()),
                ('significantAwards', models.CharField(max_length=1055)),
                ('customerName1', models.CharField(max_length=255)),
                ('sales1', models.IntegerField()),
                ('automotive1', models.BooleanField()),
                ('customerName2', models.CharField(max_length=255)),
                ('sales2', models.IntegerField()),
                ('automotive2', models.BooleanField()),
                ('customerName3', models.CharField(max_length=255)),
                ('sales3', models.IntegerField()),
                ('automotive3', models.BooleanField()),
                ('manufacturingLocations', models.CharField(max_length=1055)),
                ('event', models.CharField(max_length=1055)),
                ('OEMS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.oems')),
                ('recordPerNaLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.nalocation')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('websiteUrl', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipCode', models.IntegerField()),
                ('GeneralContact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.generalcontact')),
                ('SalesContact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.salescontact')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.country')),
            ],
        ),
        migrations.CreateModel(
            name='DiverseCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinorityOwnedBusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.businessandcertification')),
                ('OtherCertification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.othercertification')),
                ('VeteranOwnedBusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.veteranownedbusiness')),
                ('WomenOwnedBusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.womenownedbusiness')),
            ],
        ),
        migrations.CreateModel(
            name='ABCCorporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.companydetails')),
                ('diverseCertification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.diversecertification')),
                ('generalContantInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.generalcontactinfo')),
                ('productAndService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.productandservice')),
                ('productionCapabilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.productioncapabilities')),
            ],
        ),
    ]
