# Generated by Django 3.1.4 on 2022-03-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessandcertification',
            name='expirationDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='certificationExpectedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='othercertification',
            name='expirationDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='veteranownedbusiness',
            name='expirationDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='womenownedbusiness',
            name='expirationDate',
            field=models.DateField(),
        ),
    ]
