# Generated by Django 2.1.15 on 2022-03-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20220302_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othercertification',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='womenownedbusiness',
            name='ethnicity',
        ),
        migrations.AddField(
            model_name='productioncapabilities',
            name='JIT',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productioncapabilities',
            name='VMI',
            field=models.BooleanField(default=False),
        ),
    ]
