# Generated by Django 2.1.15 on 2022-03-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20220308_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veteranownedbusiness',
            name='ethnicity',
        ),
    ]
