# Generated by Django 2.1.15 on 2022-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_veteranownedbusiness_ethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='numberOfEmployees',
            field=models.BigIntegerField(),
        ),
    ]
