# Generated by Django 2.1.15 on 2022-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20220308_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEmailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=1055)),
                ('to', models.CharField(max_length=1055)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=1055)),
                ('to', models.CharField(max_length=1055)),
            ],
        ),
        migrations.AddField(
            model_name='abccorporation',
            name='emailed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='abccorporation',
            name='response',
            field=models.IntegerField(default=0),
        ),
    ]
