# Generated by Django 2.1.15 on 2022-03-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20220323_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='presentation_file',
            field=models.CharField(default='', max_length=255),
        ),
    ]
