# Generated by Django 2.1.15 on 2022-04-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_feedback_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
