# Generated by Django 2.1.15 on 2022-04-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='application_id',
            field=models.IntegerField(default=0),
        ),
    ]
