# Generated by Django 2.1.15 on 2022-04-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abccorporation',
            name='emailed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abccorporation',
            name='response',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='application_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generalcontact',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='generalcontact',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='generalcontactinfo',
            name='zip_code',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='npmsubcategory',
            name='parent_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pmsubcategory',
            name='parent_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productioncapabilities',
            name='percentage_sale',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productioncapabilities',
            name='sales1',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productioncapabilities',
            name='sales2',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='productioncapabilities',
            name='sales3',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='salescontact',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='salescontact',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
