# Generated by Django 2.1.15 on 2022-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20220410_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalcontact',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salescontact',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
