# Generated by Django 2.1.15 on 2022-04-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20220410_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessandcertification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='othercertification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veteranownedbusiness',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='womenownedbusiness',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
