# Generated by Django 2.1.15 on 2022-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20220410_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='certification_expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
