# Generated by Django 2.1.15 on 2022-04-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20220410_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncapabilities',
            name='percentage_sale',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
