# Generated by Django 2.1.15 on 2022-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20220410_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productandservice',
            name='additoinal_product_and_services',
            field=models.CharField(blank=True, max_length=1055, null=True),
        ),
        migrations.AlterField(
            model_name='productandservice',
            name='npm_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productandservice',
            name='npm_value_category1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productandservice',
            name='npm_value_category2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productandservice',
            name='pm_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productandservice',
            name='pm_value_category1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productandservice',
            name='pm_value_category2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
