# Generated by Django 2.1.15 on 2022-04-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20220410_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncapabilities',
            name='event',
            field=models.CharField(blank=True, max_length=1055, null=True),
        ),
    ]
