# Generated by Django 2.1.15 on 2022-04-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20220411_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpmValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc_corporation_id', models.IntegerField()),
                ('npm_value', models.CharField(max_length=255)),
                ('npm_value_category1', models.CharField(max_length=255)),
                ('npm_value_category2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PmValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc_corporation_id', models.IntegerField()),
                ('npm_value', models.CharField(max_length=255)),
                ('npm_value_category1', models.CharField(max_length=255)),
                ('npm_value_category2', models.CharField(max_length=255)),
            ],
        ),
    ]
