# Generated by Django 2.1.15 on 2022-04-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_npmvalues_pmvalues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmvalues',
            old_name='npm_value',
            new_name='pm_value',
        ),
        migrations.RenameField(
            model_name='pmvalues',
            old_name='npm_value_category1',
            new_name='pm_value_category1',
        ),
        migrations.RenameField(
            model_name='pmvalues',
            old_name='npm_value_category2',
            new_name='pm_value_category2',
        ),
    ]
