# Generated by Django 2.1.15 on 2022-04-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20220411_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abccorporation',
            name='product_and_service',
        ),
    ]
