# Generated by Django 2.1.15 on 2022-04-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_remove_abccorporation_product_and_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontactinfo',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=1255, null=True),
        ),
    ]
