# Generated by Django 2.1.15 on 2022-04-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_generalcontactinfo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontactinfo',
            name='company_video_file',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
