# Generated by Django 2.1.15 on 2022-05-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_generalcontactinfo_company_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.BigIntegerField(default=0)),
                ('feedback', models.CharField(blank=True, max_length=1055, null=True)),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
