# Generated by Django 2.1.15 on 2022-05-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_favoritelist_userfavoritelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritelist',
            name='application_id',
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
