# Generated by Django 2.1.15 on 2022-05-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_userfavoritelist_favorite_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontactinfo',
            name='campany_fb',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='generalcontactinfo',
            name='campany_insta',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='generalcontactinfo',
            name='campany_linkedin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='generalcontactinfo',
            name='campany_twitter',
            field=models.CharField(default='', max_length=255),
        ),
    ]
