# Generated by Django 2.1.15 on 2022-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_auto_20220522_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalcontact',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalcontact',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salescontact',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salescontact',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
