# Generated by Django 2.1.15 on 2022-05-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_auto_20220523_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalcontact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='salescontact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
