# Generated by Django 2.1.15 on 2022-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_auto_20220525_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=1055, null=True)),
                ('non_production_meterial', models.CharField(blank=True, max_length=1055, null=True)),
                ('production_meterial', models.CharField(blank=True, max_length=1055, null=True)),
                ('oems', models.CharField(blank=True, max_length=1055, null=True)),
                ('current_suppliers', models.CharField(blank=True, max_length=1055, null=True)),
                ('location', models.CharField(blank=True, max_length=1055, null=True)),
                ('response', models.BigIntegerField(default=0)),
                ('emailed', models.BigIntegerField(default=0)),
                ('action_id', models.BigIntegerField(default=0)),
            ],
        ),
    ]
